from __future__ import annotations

from copy import deepcopy
from typing import Any

from aidm_server.creatures.balance import analyze_creature_balance
from aidm_server.creatures.schemas import normalize_creature_definition


def _ability(
    ability_id: str,
    name: str,
    *,
    damage: str | None = None,
    damage_type: str = 'slashing',
    attack_bonus: int | None = None,
    description: str | None = None,
    ability_type: str = 'attack',
    range_band: str = 'melee',
    target_type: str = 'single',
    cooldown: str = 'none',
    conditions: list[str] | None = None,
    save: dict[str, Any] | None = None,
    use_when: list[str] | None = None,
) -> dict[str, Any]:
    payload: dict[str, Any] = {
        'id': ability_id,
        'name': name,
        'type': ability_type,
        'description': description or name,
        'actionCost': 'action',
        'range': range_band,
        'targetType': target_type,
        'cooldown': cooldown,
        'aiUseWhen': use_when or [],
    }
    if damage:
        payload['damage'] = {'dice': damage, 'type': damage_type}
    if attack_bonus is not None:
        payload['attackBonus'] = attack_bonus
    if conditions:
        payload['conditionsApplied'] = conditions
    if save:
        payload['save'] = save
    return payload


def _creature(
    creature_id: str,
    name: str,
    *,
    creature_type: str,
    level: int,
    tier: str,
    size: str = 'medium',
    hp: int,
    ac: int,
    scores: tuple[int, int, int, int, int, int],
    movement: dict[str, int] | None = None,
    senses: dict[str, int] | None = None,
    tags: list[str] | None = None,
    abilities: list[dict[str, Any]] | None = None,
    behavior: dict[str, Any] | None = None,
    resistances: list[str] | None = None,
    vulnerabilities: list[str] | None = None,
    immunities: list[str] | None = None,
    xp: int = 0,
    hints: list[str] | None = None,
) -> dict[str, Any]:
    strength, dexterity, constitution, intelligence, wisdom, charisma = scores
    creature = normalize_creature_definition(
        {
            'id': creature_id,
            'version': 1,
            'name': name,
            'source': 'core_bestiary',
            'descriptionShort': f'A reliable core bestiary {name.lower()}.',
            'descriptionLong': f'{name} is a reusable encounter creature with deterministic combat behavior and bounded mechanics.',
            'creatureType': creature_type,
            'visualTags': tags or [creature_type],
            'level': level,
            'challengeTier': tier,
            'size': size,
            'stats': {
                'maxHp': hp,
                'armorClass': ac,
                'strength': strength,
                'dexterity': dexterity,
                'constitution': constitution,
                'intelligence': intelligence,
                'wisdom': wisdom,
                'charisma': charisma,
            },
            'movement': movement or {'walk': 30},
            'senses': senses or {'passivePerception': 10},
            'resistances': resistances or [],
            'vulnerabilities': vulnerabilities or [],
            'immunities': immunities or [],
            'abilities': abilities or [],
            'behavior': behavior or {},
            'xpReward': xp,
            'aiNarrationHints': hints or [],
        },
        source='core_bestiary',
    )
    creature['balance'] = analyze_creature_balance(
        creature,
        party_level=max(1, level),
        party_size=4,
        target_difficulty=tier,
    )
    creature['balance']['reviewed'] = True
    return creature


CORE_BESTIARY: list[dict[str, Any]] = [
    _creature(
        'wolf',
        'Wolf',
        creature_type='beast',
        level=1,
        tier='easy',
        size='medium',
        hp=11,
        ac=13,
        scores=(12, 15, 12, 3, 12, 6),
        movement={'walk': 40},
        senses={'passivePerception': 13},
        tags=['beast', 'pack', 'predator'],
        abilities=[
            _ability(
                'wolf_bite',
                'Bite',
                damage='1d6+2',
                damage_type='piercing',
                attack_bonus=4,
                conditions=['prone'],
                save={'ability': 'str', 'dc': 11, 'effectOnSuccess': 'none'},
                description='The wolf bites and may drag a target off balance.',
                use_when=['Target is isolated, wounded, or already threatened by another wolf.'],
            )
        ],
        behavior={
            'intelligenceProfile': 'animal',
            'combatRole': 'beast',
            'primaryGoal': 'feed',
            'aggression': 55,
            'selfPreservation': 75,
            'morale': 50,
            'fleeThreshold': 35,
            'targetPriority': ['isolated', 'wounded', 'nearest'],
            'tactics': ['Circle isolated prey.', 'Withdraw if badly hurt or outnumbered.'],
            'survivalRules': ['Flee if below one-third HP and no pack advantage remains.'],
            'personalityTags': ['hungry', 'territorial'],
        },
        xp=50,
        hints=['Wolves should test the party and retreat from hopeless fights.'],
    ),
    _creature(
        'goblin_skirmisher',
        'Goblin Skirmisher',
        creature_type='humanoid',
        level=1,
        tier='easy',
        size='small',
        hp=7,
        ac=14,
        scores=(8, 14, 10, 10, 8, 8),
        movement={'walk': 30, 'climb': 20},
        tags=['goblin', 'skirmisher', 'cowardly'],
        abilities=[
            _ability('goblin_scimitar', 'Scimitar', damage='1d6+2', attack_bonus=4, description='A quick curved-blade slash.'),
            _ability('goblin_shortbow', 'Shortbow', damage='1d6+2', damage_type='piercing', attack_bonus=4, range_band='far', description='A skittish ranged shot from cover.'),
        ],
        behavior={
            'intelligenceProfile': 'low_cunning',
            'combatRole': 'skirmisher',
            'primaryGoal': 'survive',
            'aggression': 45,
            'selfPreservation': 80,
            'morale': 45,
            'fleeThreshold': 35,
            'surrenderThreshold': 20,
            'targetPriority': ['lowest_armor', 'isolated', 'last_damaged_by'],
            'tactics': ['Use cover.', 'Gang up on isolated targets.', 'Run if the leader dies.'],
            'survivalRules': ['Retreat if badly hurt, leaderless, or outnumbered.'],
            'personalityTags': ['cowardly', 'pragmatic'],
        },
        xp=50,
        hints=['Goblins should not fight to the death unless trapped or fanatical.'],
    ),
    _creature(
        'zombie',
        'Zombie',
        creature_type='undead',
        level=1,
        tier='standard',
        hp=22,
        ac=8,
        scores=(13, 6, 16, 3, 6, 5),
        movement={'walk': 20},
        tags=['undead', 'mindless', 'shambling'],
        abilities=[
            _ability('zombie_slam', 'Slam', damage='1d6+1', damage_type='bludgeoning', attack_bonus=3, description='A dead-weight slam.'),
        ],
        behavior={
            'intelligenceProfile': 'mindless',
            'combatRole': 'brute',
            'primaryGoal': 'kill_party',
            'aggression': 100,
            'selfPreservation': 0,
            'morale': 100,
            'fleeThreshold': 0,
            'surrenderThreshold': 0,
            'targetPriority': ['nearest', 'last_damaged_by'],
            'tactics': ['Advance relentlessly toward the closest living target.'],
            'survivalRules': ['Never flees, negotiates, or surrenders.'],
            'personalityTags': ['mindless'],
        },
        immunities=['poison'],
        xp=50,
        hints=['Zombies are relentless and do not respond to morale.'],
    ),
    _creature(
        'skeleton',
        'Skeleton',
        creature_type='undead',
        level=1,
        tier='easy',
        hp=13,
        ac=13,
        scores=(10, 14, 12, 6, 8, 5),
        movement={'walk': 30},
        tags=['undead', 'bone', 'ranged'],
        abilities=[
            _ability('skeleton_shortsword', 'Shortsword', damage='1d6+2', damage_type='piercing', attack_bonus=4),
            _ability('skeleton_shortbow', 'Shortbow', damage='1d6+2', damage_type='piercing', attack_bonus=4, range_band='far'),
        ],
        behavior={
            'intelligenceProfile': 'mindless',
            'combatRole': 'sniper',
            'primaryGoal': 'kill_party',
            'aggression': 90,
            'selfPreservation': 0,
            'morale': 100,
            'targetPriority': ['nearest', 'lowest_armor'],
            'tactics': ['Use ranged attacks until engaged, then switch to melee.'],
            'survivalRules': ['Never flees unless controlled by a commander.'],
        },
        vulnerabilities=['bludgeoning'],
        immunities=['poison'],
        xp=50,
    ),
    _creature(
        'bandit_thug',
        'Bandit Thug',
        creature_type='humanoid',
        level=1,
        tier='standard',
        hp=16,
        ac=12,
        scores=(13, 12, 12, 10, 10, 10),
        tags=['bandit', 'humanoid', 'criminal'],
        abilities=[
            _ability('bandit_club', 'Club', damage='1d6+1', damage_type='bludgeoning', attack_bonus=3),
            _ability('bandit_crossbow', 'Light Crossbow', damage='1d8+1', damage_type='piercing', attack_bonus=3, range_band='far'),
        ],
        behavior={
            'intelligenceProfile': 'average',
            'combatRole': 'brute',
            'primaryGoal': 'steal_item',
            'aggression': 55,
            'selfPreservation': 70,
            'morale': 48,
            'fleeThreshold': 30,
            'surrenderThreshold': 20,
            'targetPriority': ['wealthy', 'wounded', 'lowest_armor'],
            'tactics': ['Intimidate first.', 'Use numbers and threats.', 'Negotiate if the robbery turns bad.'],
            'survivalRules': ['Surrender, flee, or bargain when clearly losing.'],
            'personalityTags': ['pragmatic', 'desperate'],
        },
        xp=75,
        hints=['Bandits usually want valuables more than a glorious death.'],
    ),
    _creature(
        'bandit_captain',
        'Bandit Captain',
        creature_type='humanoid',
        level=3,
        tier='hard',
        hp=42,
        ac=15,
        scores=(15, 16, 14, 12, 11, 14),
        tags=['bandit', 'leader', 'duelist'],
        abilities=[
            _ability('captain_scimitar', 'Multi Slash', damage='2d6+3', attack_bonus=5, description='A practiced pair of fast blade cuts.'),
            _ability('captain_command', 'Commanding Shout', ability_type='special', description='The captain orders an ally to reposition, protect, or focus fire.', cooldown='turn', use_when=['An ally can exploit the order immediately.']),
        ],
        behavior={
            'intelligenceProfile': 'trained',
            'combatRole': 'leader',
            'primaryGoal': 'steal_item',
            'aggression': 65,
            'selfPreservation': 65,
            'morale': 65,
            'fleeThreshold': 25,
            'surrenderThreshold': 12,
            'targetPriority': ['spellcaster', 'leader', 'wounded'],
            'tactics': ['Direct allies.', 'Focus fire on exposed targets.', 'Call retreat if the gang breaks.'],
            'survivalRules': ['May negotiate for safe passage when badly outmatched.'],
            'personalityTags': ['pragmatic', 'disciplined'],
        },
        xp=450,
    ),
    _creature(
        'cultist',
        'Cultist',
        creature_type='humanoid',
        level=1,
        tier='easy',
        hp=9,
        ac=12,
        scores=(11, 12, 10, 10, 11, 12),
        tags=['cultist', 'fanatical', 'ritual'],
        abilities=[
            _ability('cultist_dagger', 'Dagger', damage='1d4+1', damage_type='piercing', attack_bonus=3),
            _ability('cultist_hex', 'Dark Hex', ability_type='spell', damage='1d6', damage_type='necrotic', range_band='near', save={'ability': 'wis', 'dc': 11, 'effectOnSuccess': 'half_damage'}, cooldown='once_per_combat'),
        ],
        behavior={
            'intelligenceProfile': 'average',
            'combatRole': 'controller',
            'primaryGoal': 'complete_ritual',
            'aggression': 70,
            'selfPreservation': 35,
            'morale': 55,
            'fleeThreshold': 15,
            'targetPriority': ['ritual_interruptor', 'spellcaster', 'nearest'],
            'tactics': ['Protect the ritualist.', 'Delay rather than chase if the objective matters.'],
            'survivalRules': ['Fanatics may stay longer than sane enemies, but can still break if the ritual fails.'],
            'personalityTags': ['fanatical'],
        },
        xp=50,
    ),
    _creature(
        'cult_leader',
        'Cult Leader',
        creature_type='humanoid',
        level=4,
        tier='boss',
        hp=78,
        ac=14,
        scores=(10, 14, 14, 14, 13, 16),
        tags=['cultist', 'leader', 'boss', 'ritual'],
        abilities=[
            _ability('leader_ritual_blast', 'Ritual Blast', ability_type='spell', damage='2d8+3', damage_type='necrotic', range_band='far', attack_bonus=6),
            _ability('leader_fear_prayer', 'Fear Prayer', ability_type='special', conditions=['frightened'], range_band='area', target_type='multiple', save={'ability': 'wis', 'dc': 14, 'effectOnSuccess': 'none'}, cooldown='once_per_combat'),
            _ability('leader_lair_surge', 'Lair Surge', ability_type='lair', damage='1d8', damage_type='necrotic', range_band='area', target_type='area', cooldown='recharge_5_6'),
        ],
        behavior={
            'intelligenceProfile': 'tactical',
            'combatRole': 'boss',
            'primaryGoal': 'complete_ritual',
            'aggression': 80,
            'selfPreservation': 55,
            'morale': 75,
            'fleeThreshold': 15,
            'targetPriority': ['ritual_interruptor', 'healer', 'spellcaster'],
            'tactics': ['Use minions as shields.', 'Protect ritual progress.', 'Exploit lair hazards.'],
            'survivalRules': ['May sacrifice minions or bargain only if the ritual can still be preserved.'],
            'personalityTags': ['fanatical', 'arrogant'],
        },
        xp=1100,
    ),
    _creature(
        'guard',
        'Guard',
        creature_type='humanoid',
        level=1,
        tier='standard',
        hp=15,
        ac=16,
        scores=(13, 12, 12, 10, 11, 10),
        tags=['guard', 'disciplined', 'law'],
        abilities=[_ability('guard_spear', 'Spear', damage='1d6+1', damage_type='piercing', attack_bonus=3)],
        behavior={
            'intelligenceProfile': 'trained',
            'combatRole': 'tank',
            'primaryGoal': 'protect_location',
            'aggression': 45,
            'selfPreservation': 60,
            'morale': 60,
            'fleeThreshold': 25,
            'surrenderThreshold': 15,
            'targetPriority': ['immediate_threat', 'armed', 'nearest'],
            'tactics': ['Hold a line.', 'Call for backup.', 'Prioritize nonlethal capture when appropriate.'],
            'survivalRules': ['Fall back to regroup if alone and badly injured.'],
            'personalityTags': ['disciplined'],
        },
        xp=75,
    ),
    _creature(
        'mercenary',
        'Mercenary',
        creature_type='humanoid',
        level=2,
        tier='standard',
        hp=27,
        ac=14,
        scores=(14, 13, 14, 10, 11, 11),
        tags=['mercenary', 'trained', 'pragmatic'],
        abilities=[
            _ability('mercenary_longsword', 'Longsword', damage='1d8+2', attack_bonus=4),
            _ability('mercenary_crossbow', 'Crossbow', damage='1d8+1', damage_type='piercing', attack_bonus=3, range_band='far'),
        ],
        behavior={
            'intelligenceProfile': 'trained',
            'combatRole': 'brute',
            'primaryGoal': 'survive',
            'aggression': 60,
            'selfPreservation': 70,
            'morale': 60,
            'fleeThreshold': 25,
            'surrenderThreshold': 15,
            'targetPriority': ['spellcaster', 'leader', 'wounded'],
            'tactics': ['Use terrain.', 'Coordinate with allies.', 'Stop fighting if the contract is no longer worth dying for.'],
            'survivalRules': ['Negotiate withdrawal when pay is not worth the risk.'],
            'personalityTags': ['pragmatic', 'disciplined'],
        },
        xp=200,
    ),
    _creature(
        'giant_spider',
        'Giant Spider',
        creature_type='beast',
        level=2,
        tier='hard',
        size='large',
        hp=26,
        ac=14,
        scores=(14, 16, 12, 2, 11, 4),
        movement={'walk': 30, 'climb': 30},
        senses={'darkvision': 60, 'passivePerception': 10},
        tags=['spider', 'ambusher', 'poison'],
        abilities=[
            _ability('spider_bite', 'Venomous Bite', damage='1d8+3', damage_type='piercing', attack_bonus=5, description='A bite that injects weakening venom.'),
            _ability('spider_web', 'Web', ability_type='special', conditions=['restrained'], range_band='near', save={'ability': 'dex', 'dc': 12, 'effectOnSuccess': 'none'}, cooldown='recharge_5_6'),
        ],
        behavior={
            'intelligenceProfile': 'animal',
            'combatRole': 'ambusher',
            'primaryGoal': 'feed',
            'aggression': 70,
            'selfPreservation': 65,
            'morale': 55,
            'fleeThreshold': 25,
            'targetPriority': ['restrained', 'isolated', 'wounded'],
            'tactics': ['Open from hiding.', 'Web isolated prey.', 'Retreat into darkness if hurt.'],
            'survivalRules': ['Abandon prey if fire or heavy injury makes the hunt unsafe.'],
            'personalityTags': ['hungry'],
        },
        xp=450,
    ),
    _creature(
        'rat_swarm',
        'Rat Swarm',
        creature_type='swarm',
        level=1,
        tier='easy',
        size='medium',
        hp=18,
        ac=10,
        scores=(9, 11, 9, 2, 10, 3),
        movement={'walk': 30, 'climb': 20},
        tags=['swarm', 'beast', 'vermin'],
        abilities=[_ability('rat_swarm_bites', 'Swarming Bites', damage='2d6', damage_type='piercing', attack_bonus=2)],
        behavior={
            'intelligenceProfile': 'animal',
            'combatRole': 'minion',
            'primaryGoal': 'feed',
            'aggression': 65,
            'selfPreservation': 45,
            'morale': 40,
            'fleeThreshold': 20,
            'targetPriority': ['downed', 'wounded', 'nearest'],
            'tactics': ['Overwhelm one target.', 'Scatter from fire or thunder.'],
            'survivalRules': ['Scatter if badly damaged by area effects.'],
            'personalityTags': ['hungry', 'desperate'],
        },
        resistances=['bludgeoning', 'piercing', 'slashing'],
        xp=50,
    ),
    _creature(
        'slime',
        'Slime',
        creature_type='ooze',
        level=1,
        tier='standard',
        hp=19,
        ac=8,
        scores=(12, 6, 14, 1, 6, 2),
        movement={'walk': 20, 'climb': 10},
        senses={'blindsight': 30, 'passivePerception': 8},
        tags=['ooze', 'acid', 'mindless'],
        abilities=[_ability('slime_pseudopod', 'Acidic Pseudopod', damage='1d8+1', damage_type='acid', attack_bonus=3)],
        behavior={
            'intelligenceProfile': 'mindless',
            'combatRole': 'brute',
            'primaryGoal': 'feed',
            'aggression': 90,
            'selfPreservation': 0,
            'morale': 100,
            'targetPriority': ['nearest'],
            'tactics': ['Absorb whatever it can reach.'],
            'survivalRules': ['Never negotiates or surrenders.'],
        },
        resistances=['acid'],
        immunities=['poison'],
        xp=100,
    ),
    _creature(
        'wraith',
        'Wraith',
        creature_type='undead',
        level=5,
        tier='deadly',
        hp=67,
        ac=13,
        scores=(6, 16, 16, 12, 14, 15),
        movement={'walk': 0, 'fly': 60},
        senses={'darkvision': 60, 'passivePerception': 12},
        tags=['undead', 'incorporeal', 'necrotic'],
        abilities=[
            _ability('wraith_life_drain', 'Life Drain', damage='3d8+3', damage_type='necrotic', attack_bonus=6, description='The wraith drains vitality with a chilling touch.'),
            _ability('wraith_terror', 'Terror Drift', ability_type='special', conditions=['frightened'], range_band='near', save={'ability': 'wis', 'dc': 14, 'effectOnSuccess': 'none'}, cooldown='once_per_combat'),
        ],
        behavior={
            'intelligenceProfile': 'alien',
            'combatRole': 'assassin',
            'primaryGoal': 'kill_party',
            'aggression': 85,
            'selfPreservation': 45,
            'morale': 70,
            'fleeThreshold': 20,
            'targetPriority': ['isolated', 'wounded', 'low_wisdom'],
            'tactics': ['Strike from darkness.', 'Avoid being surrounded.', 'Exploit fear and isolation.'],
            'survivalRules': ['Fade away if its anchor is threatened or the fight turns against it.'],
            'personalityTags': ['vengeful', 'sadistic'],
        },
        resistances=['cold', 'necrotic'],
        immunities=['poison'],
        xp=1800,
    ),
]


CORE_BESTIARY_BY_ID = {creature['id']: creature for creature in CORE_BESTIARY}


def core_bestiary() -> list[dict[str, Any]]:
    return [deepcopy(creature) for creature in CORE_BESTIARY]


def core_creature(creature_id: str) -> dict[str, Any] | None:
    creature = CORE_BESTIARY_BY_ID.get(creature_id)
    return deepcopy(creature) if creature else None
